### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by KingMob** [quavarus/Spotify.bundle#10]
I keep seeing "Preferences: Username or Password is not correct", but I've double-checked with both web login and the app login, and they're correct. FWIW, my password does have unusual characters, but nothing that can't be typed easily.

Under "About", the only error is "Data Service Status: Authentication Failed".

<img width="613" alt="screen shot 2017-10-14 at 1 35 50 am" src="https://user-images.githubusercontent.com/946421/31572977-114cd5f8-b080-11e7-88fd-8be67d8ce5d4.png">

**Comment by julbart** [comment]
Hi,

I had the same problem and after many debug I find a way for me:
Replace in Spotify.bundle\Contents\Code\metadata.py : 

`      postValues["code"]=params['code']
      postValues["redirect_uri"]=String.Quote(CALLBACK_URL)`

By:

`      postValues["code"]=String.Quote(params['code'])
      postValues["redirect_uri"]=CALLBACK_URL`

In the log we can saw the json without my fix:
'code' : u'thecodehere' and not 'code' : 'thecodehere'
and the CALLBACK_URL is "https%3A//quavarus.github.io/Spotify.bundle/Web/callback.htm" and not "https://quavarus.github.io/Spotify.bundle/Web/callback.htm"

I hope this help you and other member.
Only issue I found: play on remote device via iOS App (to send play on remote device like browser or A/V) not working, but for this I need help

**Comment by quavarus** [comment]
Thanks @julbart for the time spent debugging and the fix. I've updated the plugin.
